/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MKL25Z128xxx4
package_id: MKL25Z128VLK4
mcu_data: ksdk2_0
processor_version: 13.0.1
board: FRDM-KL25Z
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1}
  - {pin_num: '27', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
	// =========================================
	// Port A - UART0 (Bluetooth) + Motor PWM
	// =========================================
    CLOCK_EnableClock(kCLOCK_PortA);
    /* PORTA1 (pin 27) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_RX_PORT, BOARD_INITPINS_DEBUG_UART_RX_PIN, kPORT_MuxAlt2);
    /* PORTA2 (pin 28) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_TX_PORT, BOARD_INITPINS_DEBUG_UART_TX_PIN, kPORT_MuxAlt2);
    // PTA4 = TPM0_CH1 (Motor Left PWM) - configured in motor.c
    // PTA5 = TPM0_CH2 (Motor Right PWM) - configured in motor.c

    SIM->SOPT5 = ((SIM->SOPT5 &
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));

	// =========================================
	// Port B - ADC (LDR) + Motor Direction
	// =========================================
	CLOCK_EnableClock(kCLOCK_PortB);
	PORT_SetPinMux(PORTB, 0U, kPORT_PinDisabledOrAnalog); // PTB0 - LDR (ADC0_SE8)
	// PTB1, PTB2, PTB3 = Motor direction pins - configured in motor.c

	// =========================================
	// Port C - LED + Motor Direction + Ultrasonic
	// =========================================
	CLOCK_EnableClock(kCLOCK_PortC);
	PORT_SetPinMux(PORTC, 1U, kPORT_MuxAsGpio);  // PTC1 - LED Headlight
	// PTC2 = Motor Right IN2 - configured in motor.c
	// PTC8, PTC9 = Ultrasonic TRIG/ECHO - configured in ultrasonic.c

	// =========================================
	// Port D - DHT11 only
	// =========================================
	CLOCK_EnableClock(kCLOCK_PortD);
	PORT_SetPinMux(PORTD, 4U, kPORT_MuxAsGpio);  // PTD4 - DHT11 Data
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
